config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'page/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: {
                 sessions: 'users/sessions',
                 confirmations: 'users/confirmations',
                 unlocks: 'users/unlocks',
                 registrations: 'users/registrations',
                 passwords: 'users/passwords'
             },
             path: '/',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
             }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      controller :page do
        get 'home', as: :home_page
        get 'email', as: :email_page
        get 'map', as: :map_page
      end
    end
  end
end

app/views/pages/_form.html.slim
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :controller
    = f.text_field :controller
  .field
    = f.label :action
    = f.text_field :action
  .field
    = f.label :tracking
    = f.check_box :tracking
  .actions = f.submit

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

=> link_to 'Show', @page
'|
=< link_to 'Back', pages_path

app/views/pages/index.html.slim
h1 Listing pages

table
  thead
    tr
      th Controller
      th Action
      th Tracking
      th
      th
      th

  tbody
    - @pages.each do |page|
      tr
        td = page.controller
        td = page.action
        td = page.tracking
        td = link_to 'Show', page
        td = link_to 'Edit', edit_page_path(page)
        td = link_to 'Destroy', page, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Page', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.slim
p#notice = notice

p
  strong Controller:
  = @page.controller
p
  strong Action:
  = @page.action
p
  strong Tracking:
  = @page.tracking

=> link_to 'Edit', edit_page_path(@page)
'|
=< link_to 'Back', pages_path