config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'page/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: {
                 sessions: 'users/sessions',
                 confirmations: 'users/confirmations',
                 unlocks: 'users/unlocks',
                 registrations: 'users/registrations',
                 passwords: 'users/passwords'
             },
             path: '/',
             path_names: {
                 sign_in: 'login',
                 sign_out: 'logout'
             }

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users/sessions#new', as: :unauthenticated_root
    end

    authenticate :user do
      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations

      controller :page do
        get 'home', as: :home_page
        get 'email', as: :email_page
        get 'map', as: :map_page
      end
    end
  end
end

app/views/layouts/_footer.slim
.container-fluid.container-fixed-lg.footer
  .copyright.sm-text-center
    p.small.no-margin.pull-left.sm-pull-reset
      span.hint-text Copyright © 2014
    .clearfix

app/views/layouts/_header.slim
.header.light
  /! START MOBILE SIDEBAR TOGGLE
  a.btn-link.toggle-sidebar.d-lg-none.pg.pg-menu data-toggle="sidebar" href="#"
  div
    .brand.inline
      = image_tag 'logo.png', alt: 'logo', height: 22, width: 78, data: { src: image_path('logo.png'), 'src-retina': image_path('logo_2x.png') }
    = link_to 'Home', home_page_path, class: 'btn btn-link text-primary m-l-20 d-none d-lg-inline-block d-xl-inline-block', data: {turbolinks: false}
    = link_to 'Email', email_page_path, class: 'btn btn-link text-primary m-l-20 d-none d-lg-inline-block d-xl-inline-block', data: {turbolinks: false}
    = link_to 'Map', map_page_path, class: 'btn btn-link text-primary m-l-20 d-none d-lg-inline-block d-xl-inline-block', data: {turbolinks: false}
  .d-flex.align-items-center
    /! START User Info
    .pull-left.p-r-10.fs-14.font-heading.d-lg-inline-block.d-none.m-l-20
      span.semi-bold = current_user.email
    .dropdown.pull-right.d-lg-inline-block.d-none
      button.profile-dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
        span.thumbnail-wrapper.d32.circular.inline.bg-master-light
          = icon('fas', 'user')
      .dropdown-menu.dropdown-menu-right.profile-dropdown role="menu"
        a.dropdown-item href="javascript:;"
          i.pg-settings_small
          | Settings
        = link_to destroy_user_session_path, class: 'clearfix bg-master-lighter dropdown-item', method: :delete do
          span.pull-left Logout
          span.pull-right
            i.pg-power

app/views/layouts/_sidebar.slim
nav.page-sidebar data-pages="sidebar"
  /! BEGIN SIDEBAR MENU TOP TRAY CONTENT
  #appMenu.sidebar-overlay-slide.from-top

  /! BEGIN SIDEBAR MENU HEADER
  .sidebar-header
    = image_tag 'logo.png', alt: 'logo', height: 22, width: 78, data: { src: image_path('logo.png'), 'src-retina': image_path('logo_2x.png') }

  /! START SIDEBAR MENU
  .sidebar-menu
    /! BEGIN SIDEBAR MENU ITEMS
    ul.menu-items
      li.m-t-30
        = link_to authenticated_root_path do
          span.title Dashboard
        span.icon-thumbnail
          = icon "fas", "tachometer-alt "
      li
        = link_to user_registrations_path do
          span.title Users
        span.icon-thumbnail
          = icon "fas", "users"
      li
        = link_to pages_path do
          span.title Pages
        span.icon-thumbnail
          i.pg-ui
    .clearfix

app/views/layouts/application.slim
doctype html
html
  head
    title TimeTracking
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': false

  body.fixed-header.dashboard.menu-pin
    /! BEGIN SIDEBAR
    = render 'layouts/sidebar'

    /! START PAGE-CONTAINER
    .page-container

      /! START HEADER
      = render 'layouts/header'

      /! START PAGE CONTENT WRAPPER
      .page-content-wrapper.full-height
        /! START PAGE CONTENT
        .content.sm-gutter.full-height
          /! START JUMBOTRON
          div data-pages="parallax"
            .container-fluid.p-l-25.p-r-25.sm-p-l-0.sm-p-r-0
              .inner
                /! START BREADCRUMB
                ol.breadcrumb
                  li.breadcrumb-item
                    a href="#"  Home
                  li.breadcrumb-item.active View

          /! START CONTAINER FLUID
          .container-fluid.p-l-25.p-r-25.p-t-0.p-b-25.sm-padding-10.full-height
            /! BEGIN PlACE PAGE CONTENT HERE
            = yield

        /! START FOOTER
        = render 'layouts/footer'

    = yield :javascript

app/views/layouts/blank.slim
doctype html
html
  head
    title TimeTracking
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'frontend', media: 'all', 'data-turbolinks-track': 'reload'

  body.fixed-header.menu-pin
    = yield

    = javascript_include_tag 'frontend', 'data-turbolinks-track': 'reload'